//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEU
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPelicula
    {
        [ScaffoldColumn(false)]
        public int id { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre es requerido"), MaxLength(55)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha de estreno")]
        public Nullable<System.DateTime> estreno { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La categoría es requerida"), MaxLength(55)]
        [Display(Name = "Categoria")]
        public string categoria { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La duracion es requerida"), MaxLength(55)]
        [Display(Name = "Duracion")]
        public string duracion { get; set; }
    }
}
